[project]
name = "smart-aircon"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "django>=5.2.1",
    "mysqlclient>=2.2.7",
    "uvicorn>=0.34.3",
]
