# Generated by Django 5.2.1 on 2025-06-09 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0002_airconlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='AirconUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_aircon_on', models.BooleanField(default=False)),
                ('usage_duration', models.FloatField(default=0.0)),
            ],
        ),
    ]
