# Generated by Django 5.2.1 on 2025-06-10 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0003_airconusagelog'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAirconSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_temp_max', models.FloatField(default=28.0, help_text='에어컨 켜는 온도')),
                ('target_humidity_max', models.FloatField(default=60.0, help_text='에어컨 켜는 습도(%)')),
                ('auto_control_enabled', models.BooleanField(default=False, help_text='자동 제어 활성화')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
